### ISSUE TITLE
Broken on Chrome on Android due to Chromium Issue 358198

### ISSUE THREAD

**Issue by hawksley** [hawksley/eleVR-Web-Player#11]
As a result of a security bug, all videos are marked as cross-origin and can't be accessed by the player.

"We landed a hack earlier to treat all video urls as cross-origin for an security issue.
That fix, however, breaks all webgl tests that has video in it."

See Chromium issue 358198 for more details:
https://code.google.com/p/chromium/issues/detail?id=358198

This is not fixable on our end. Users facing this issue are advised to try using another browser (eg. Firefox).

**Comment by hawksley** [comment]
Most recent update appears to be that this bug is listed as fixed, but still appears to be broken according to at least one user report. I will look into it further likely next week.

**Comment by alexmgrau** [comment]
Broken for us too. Both players working in Chrome Beta on Android.

**Comment by hawksley** [comment]
huh. I wonder if the fix is simply not out to regular chrome yet and is still only in the beta.

**Comment by hawksley** [comment]
Also, thanks for checking it out. I don't have an Android phone, and I'm about to go to a conference, so my ability to debug this is a bit delayed.

**Comment by alexmgrau** [comment]
Yeah, Android Chrome has broken WebGL video textures a few times (for both local and CORS). I agree that it is likely out of our hands and should be fixed in a future release of regular Chrome. I have the same result on a Note 4 with Lollipop and a LG G2 with KitKat. 

Also, while this comment should be listed under #9, we have a hack for iPhone that allows some playback on recent iPhones (iPad already covered by webkit-playsinline). Can see if I can incorporate it into a recent version of the eleVR player if you are interested.

**Comment by hawksley** [comment]
That would be awesome if you could do that! It's pretty annoying that even with webgl that this doesn't work for iphones by default.

**Comment by alexmgrau** [comment]
After a Chrome update, both players are now working on Note 4 and LG G2.

Additionally, I forked the eleVR player and added the iPhone video hack. May add the iPhone audio hack if I get some free time. Not great but better than nothing.

**Comment by yang3kui** [comment]
I have upated my chrome to ver: 44.0.2403.133, released on 2015/07/31. However, the web player is still not working. I also tried chrome dev, ver: 45.0.2454.12,  with no lucky. My device was a MI 4, and i will test on Note 4 next monday.  @alexmgrau  what is the version number of your Chrome.

**Comment by hawksley** [comment]
This is working for me on chrome 44.0.2403.133 on a nexus 7 tablet.

**Comment by hawksley** [comment]
@yang3kui does it work for you on the Note 4? It does look to me like the original issue was fixed in chrome 44.0.2403.133 as verified by @alexmgrau and myself at this point. I'm not sure what the issue that you are now facing is, but it is looking to be device specific. I have no access to a MI 4, so that's going to be hard to debug.

**Comment by hawksley** [comment]
I'm closing this because it clearly works on all 3 android devices that I've been able to test on, and there has been no additional update from @yang3kui
